AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: my-iam-user-name

  MyEC2Policy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: my-ec2-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ec2:RunInstances
            Resource: '*'
          - Effect: Deny
            Action:
              - ec2:TerminateInstances
              - ec2:StopInstances
            Resource: '*'
      Users:
        - !Ref 'MyIAMUser'
